### ISSUE TITLE
Possible way to increase performance

### ISSUE THREAD

**Issue by lrberge** [kylebutts/rademacher#2]
Hi Kyle, very cool small project!

I've been peering at the code and I have a comment on the following line:
> IntegerVector random_integer = sample(2147483647, num_integers, true);

This line is kinda slow because i) you create a vector (which will later require access), ii) this is a by-product of a simple random number (typically int64) that has been generated to produce the output.

My suggestion is to hard code the number generating process directly, so that:
- you can apply your algorithm to int64 directly (instead of int32)
- you can generate new random int64s on-the-fly, only when needed (and close to the processor, likely without ever leaving the L1 cache)

The [Splitmix64](https://rosettacode.org/wiki/Pseudo-random_numbers/Splitmix64) random number generator algorithm is simple and cool. You just need to feed it the seed (e.g. init at clock time).

I'm not sure it would change everything because your algorithm is already pretty fast, but I think you would get closer to the theoretical limit.

=> This is just a comment. Feel free to close!

**Comment by kylebutts** [comment]
FYI, a faster version is merged directly into `dqrng` (https://github.com/daqana/dqrng/pull/50) doing as you said, grabbing a single int at a time. I think that's probably as fast as it can get unless you want to sacrifice some of the randomness quality. Honestly, might not make a meaningful difference in actual uses. 

I should probably do the same in this package for ppl that want a dependency-less version. 

The main thing I have been meaning to do with this is to speed up bootstrapping standard errors. Basically, you calculate $X' R_p$ where $X$ is an $n \times k$ matrix and $R_p$ is a $n \times B$ matrix of rademacher draws. I would want to parallelize it by column (to keep the column in the cache) dot product using the same RNG seed each time. Your link to Splitmix64 might work really well.

**Comment by lrberge** [comment]
Ah, indeed, it's the same idea as in `dqrng`!  Sorry for the comment then! :-)

+1 for the column-parallel method. In that case the speed up may be 1 to 1, very good idea.

BTW I'll contact you soon on another matter (`fixest` :-))

**Comment by kylebutts** [comment]
For the record, it seems to be the 64-bit vs 32-bit that speeds-up dqrng. I did as you said and generated a single int on the fly and it doesn't really make a difference. Switching to 64-bit generator did help (I manually set the seed just to see if it speeds things up):
``` cpp
#include <Rcpp.h>
using namespace Rcpp;


// Create a uint32_t using R's PRNGs. 
// 
// source: https://github.com/daqana/dqrng/blob/9e83c4d035a2ef41c42171e38adeb47a4f9d2003/inst/include/R_randgen.h#L18
inline uint32_t R_random_u32() {
    constexpr double upper_limit=4294967296;
    double val = R_unif_index(upper_limit);
    if (val >= upper_limit) { val = 0; } // Absolutely avoid overflow.
    return static_cast<uint32_t>(val);
}

//' Sample Bernoulli(0.5) distribution really fast
//'
//' @description This uses a fancy trick to draw Bernoulli(0.5) r.v.s
//'   quickly. To do so, the function draws from 1:(2^31 - 1), and then
//'   uses each bit of the integer to determine 31 values of 0/1. This
//'   allows for 31 0/1 random variables to be drawn per random draw.
//'
//' @param n Integer, number of random variables to draw
//'
//' @return integer vector of length n with values -1 or 1
//'
//' @export
// [[Rcpp::export]]
IntegerVector sample_0_1_32(int n)
{
  if (n < 0)
  {
    stop("n must be a positive integer");
  }
  if (n > 2147483647)
  {
    stop("n must be less than 2147483647");
  }

  // Calculate the number of integers needed based on N
  int num_integers = ceil(n / 31.0);

  IntegerVector res = no_init(n);
  R_len_t k = 0;
  int J = 30;
  int bits;
  for (R_len_t i = 0; i < num_integers - 1; i++)
  {
    bits = R_random_u32();

    for (int j = 0; j <= J; ++j, ++k)
    {
      res[k] = ((bits >> j) & 1);
    }
  }

  bits = R_random_u32();
  for (int j = 0; k < n; ++j, ++k)
  {
    res[k] = ((bits >> j) & 1);
  }

  return res;
}



// 64-bit version
class Splitmix64
{
public:
  Splitmix64() { state = 0; }
  Splitmix64(const uint64_t seed) : state(seed) {}

  void seed(const uint64_t seed)
  {
    state = seed;
  }

  uint64_t next_int()
  {
    uint64_t z = (state += 0x9e3779b97f4a7c15);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9;
    z = (z ^ (z >> 27)) * 0x94d049bb133111eb;
    return z ^ (z >> 31);
  }

private:
  uint64_t state;
  const double twoPower64 = pow(2.0, 64);
};

//' Sample Bernoulli(0.5) distribution really fast
//'
//' @description This uses a fancy trick to draw Bernoulli(0.5) r.v.s
//'   quickly. To do so, the function draws from 1:(2^31 - 1), and then
//'   uses each bit of the integer to determine 31 values of 0/1. This
//'   allows for 31 0/1 random variables to be drawn per random draw.
//'
//' @param n Integer, number of random variables to draw
//'
//' @return integer vector of length n with values -1 or 1
//'
//' @export
// [[Rcpp::export]]
IntegerVector sample_0_1(int n)
{
  if (n < 0)
  {
    stop("n must be a positive integer");
  }
  if (n > 2147483647)
  {
    stop("n must be less than 2147483647");
  }

  IntegerVector res = no_init(n);
  Splitmix64 random;
  random.seed(1234567);

  // Calculate the number of integers needed based on N
  int num_integers = ceil(n / 63.0);
  
  // Do RNG
  R_len_t k = 0;
  int J = 62;
  uint64_t bits;
  for (R_len_t i = 0; i < num_integers - 1; i++)
  {
    bits = random.next_int();
    for (int j = 0; j <= J; ++j, ++k)
    {
      res[k] = ((bits >> j) & 1);
    }
  }

  // Avoid needing if statement through all of this
  // https://github.com/daqana/dqrng/pull/50#discussion_r1249571555
  bits = random.next_int();
  for (int j = 0; k < n; ++j, ++k)
  {
    res[k] = ((bits >> j) & 1);
  }

  return res;
}
```

It gives about the same speedup as `dqrng`:
```
r$> bench::mark(
      rademacher::sample_0_1_32(1e7), 
      rademacher::sample_0_1(1e7), 
      dqrng::dqrrademacher(1e7),
      check = FALSE
    )
# A tibble: 3 × 13
  expression                            min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result memory              time            gc               
  <bch:expr>                       <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list> <list>              <list>          <list>           
1 rademacher::sample_0_1_32(1e+07)   7.72ms   8.33ms      120.    38.2MB     131.    22    24      183ms <NULL> <Rprofmem [6 × 3]>  <bench_tm [46]> <tibble [46 × 3]>
2 rademacher::sample_0_1(1e+07)      3.58ms   3.92ms      254.    38.2MB     143.    55    31      216ms <NULL> <Rprofmem [6 × 3]>  <bench_tm [86]> <tibble [86 × 3]>
3 dqrng::dqrrademacher(1e+07)        3.76ms   3.87ms      253.    38.2MB     126.    62    31      245ms <NULL> <Rprofmem [86 × 3]> <bench_tm [93]> <tibble [93 × 3]>
```

**Comment by lrberge** [comment]
Interesting. I think it boils down to the number of random numbers generated, which is twice in the 32 bits case.

**Comment by kylebutts** [comment]
Okay, two more updates. 

1. I figured out a better way to RNG ints by looking at R source code (https://github.com/wch/r-source/blob/b49e1cd58edbecdef7cde2f4c2ac46179a5adcb2/src/main/RNG.c#L874-L885)
2. I learned when using `devtools::build_readme()`, they install an unoptimized version of the package, so the benchmarks were misleading

With both changes, 32-bit is closer to 64-bit version. For that reason, I'm not going to include the 64-bit version in this package and point ppl to `dqrng`. 
``` r
library(rademacher)
#> Loading required package: Rcpp
bench::mark(
  rademacher::sample_0_1(1e7), 
  dqrng::dqrrademacher(1e7),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 × 6
#>   expression                         min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                    <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 rademacher::sample_0_1(1e+07)   5.21ms   5.38ms      182.    38.2MB     182.
#> 2 dqrng::dqrrademacher(1e+07)     3.63ms   3.86ms      255.    38.2MB     235.
```

Thanks Laurent, fun distraction! :-)

**Comment by lrberge** [comment]
> Thanks Laurent, fun distraction! :-)

Sorry for that :-) (... and I should get back to work! :-))

Perfect! In any case 3ms or 6ms for $10^7$ observations is really about splitting hairs! :-)

On point 2: I already lost a lot of time before finding this out. It's too bad `devtools` does not provide an option for turning on -O2 optimization. I had to create my own package loader to do that!
